### ISSUE TITLE
Testing debug-es/esm/browser with Jest

### ISSUE THREAD

**Issue by wrumsby** [LightouchDev/debug-es#3]
I'm trying to figure out how to test code that imports `debug-es/esm/browser` with Jest.

With my current config importing `debug-es` works, but importing `debug-es/esm/browser` doesn't.

`.babelrc`:

```
{
  "presets": [
      [
      "@babel/preset-env",
      {
        "modules": "commonjs",
        "useBuiltIns": "entry"
      }
    ]
  ]
}
```

`jest.config.js`:

```js
module.exports = {
  verbose: true,
  testURL: 'http://localhost',
  cacheDirectory: `${__dirname}/.cache`,
  moduleDirectories: [
    '/examples',
    'node_modules'
  ],
  moduleFileExtensions: [
    'js',
    'mjs'
  ],
  testMatch: [
    '**/*.test.js'
  ],
  transformIgnorePatterns: [
    '/node_modules/(?!debug-es)'
  ]
}
```

`dependencies` and `devDependencies` from `package.json`:

```json
{
  "dependencies": {
    "debug-es": "^1.2.3"
  },
  "devDependencies": {
    "@babel/core": "^7.1.0",
    "@babel/preset-env": "^7.1.0",
    "babel-core": "^7.0.0-bridge.0",
    "jest": "^23.6.0",
    "jsdom": "^12.0.0"
  }
}
```

**Comment by miaulightouch** [comment]
it seems like upstream issue, see facebook/jest#4842

by default, `import 'debug-es'` === `import 'debug-es/lib/index.js'`,
es module is still a very early staged feature for now.

**Comment by miaulightouch** [comment]
actually, for better compatibility (webpack 4), I use `.js` extension not `.mjs` for es module.

I still looking for better solution for compatibility, or just waiting es module had been supported widely.

**Comment by miaulightouch** [comment]
sorry for misunderstanding, pls follow this comment to change your config:
https://github.com/facebook/jest/issues/6229#issuecomment-403539460

**Comment by miaulightouch** [comment]
and I notice you lost `babel-jest` in your devDependencies
